### ISSUE TITLE
Invalid model name is not being rejected when creating prompt via API

### ISSUE THREAD

**Issue by arozumenko** [ProjectAlita/projectalita.github.io#120]
**Env:**

Win 11, Google Chrome
Environment: [https://eye.projectalita.ai/](https://eye.projectalita.ai/ "‌")

**Steps to reproduce:**

1. Open Create Prompt POST request in postman
2. Open Body of the request and enter "invalid model name" as "model" and "suggested model"
3. Send POST request to create prompt

**Actual result:**

Prompt is being created successfully with status code 201 even if the model name is invalid.

**Expected result:**

Error should be thrown when model name is invalid

![image.png](https://trello.com/1/cards/666b06d405466a24f40ae20d/attachments/666b08449733ec97c6a5f18a/download/image.png)

[Original Issue in Trello](https://trello.com/c/OFK7l0wW/491-invalid-model-name-is-not-being-rejected-when-creating-prompt-via-api)

![Image](https://trello.com/1/cards/666b06d405466a24f40ae20d/attachments/666b08449733ec97c6a5f18a/download/image.png)

**Comment by plageat** [comment]
Fixed in https://github.com/ProjectAlita/promptlib_shared/commit/81151f33c44af0425bcd24da4e4ecaa2ad358917

**Comment by epamLDadayan** [comment]
@plageat 

Not fixed, checked on Main:

![Image](https://github.com/user-attachments/assets/452eef5f-cb32-4d18-81ee-6667a32d9ff5)

**Comment by plageat** [comment]
Not on main yet
ETA of deployment - 22.11.2024 11:00 UTC+3

**Comment by epamLDadayan** [comment]
Fixed Checked on Main env.
