### ISSUE TITLE
[BUG] New conversation created without name and spinner persists after deleting initial message

### ISSUE THREAD

**Issue by marara-h** [ProjectAlita/projectalita.github.io#1719]
**Steps to reproduce:**  
1. Navigate to the chat section and click to create a new conversation.  
2. Observe chat name field

**Actual results:**  
- A new conversation is added without a name, and the name field shows endless spinning loader.  
- The conversation was created with the "New Conversation" name which is not displaying in FE.  

<img width="230" height="196" alt="Image" src="https://github.com/user-attachments/assets/f156eadd-2590-496a-a126-0558b72db0ff" />

<img width="501" height="259" alt="Image" src="https://github.com/user-attachments/assets/933e43a3-3a25-4b56-9c61-239da63f92d2" />

**Expected results:**  
- The conversation should not be created until a valid name is provided or the user confirms the action.  
Either the initiated "New conversation" name came from response should be displayed in FE conversation Title field

https://github.com/user-attachments/assets/eeb8c66d-a0fb-4867-b2a4-3ce03ce8ccd2

**Comment by epamLDadayan** [comment]
@marara-h seems this is fixed on DEV env.

Please recheck.

<img width="1828" height="844" alt="Image" src="https://github.com/user-attachments/assets/efbdadc6-a183-4d69-82b6-9382063baf80" />

**Comment by marara-h** [comment]
@epamLDadayan can still reproduce on Dev env, Please see the screenshot below

<img width="265" height="133" alt="Image" src="https://github.com/user-attachments/assets/e8796fe0-a55b-4a47-8769-336eade84695" />

**Comment by epamLDadayan** [comment]
@marara-h , @HawkQing1 verified on DEV env

**Comment by marara-h** [comment]
Verified on Next env
