### ISSUE TITLE
[BUG] Additional page reload is needed to show added/removed toolkits for agents/pipelines

### ISSUE THREAD

**Issue by epamLDadayan** [ProjectAlita/projectalita.github.io#1730]
Additional page reload is needed to show added/removed toolkits for agents/pipelines

Steps to reproduce:

1. Create a new agent or use an existing one.
2. Add a toolkit, agent or pipeline under Toolkits section.
3. Navigate to other section, menu.
4. Reopen the agent.
5. Check the added items under Toolkits section.

Actual Result: The entities under Toolkits section are not shown. They appear back after page reload only. They are coming from BE and properly provided.

Expected Result: The entities under Toolkits section are shown without any additional page reloads.

Note: This is also actual for removing entities under Toolkits section

**Comment by HawkQing1** [comment]
@epamLDadayan the icon issue should be fixed on dev, please verify it.

**Comment by epamLDadayan** [comment]
@HawkQing1 The icon issue is still applicable in 2 scenarios:

- when we are saving and creating a new version for agent
- when the added agent/pipeline as a toolkit has version and we switch between versions

**Comment by plageat** [comment]
> [@plageat](https://github.com/plageat) the Application version detail API doesn't return the icon_meta of the tools to FE

Fixed in https://github.com/ProjectAlita/applications/commit/906822afbaab49dc3d686c8ffa9c121655234b2c
@epamLDadayan  please check on dev env

**Comment by epamLDadayan** [comment]
@HawkQing1 , @plageat Double checked all scenarios on DEV with proper working agents and pipelines, 
- adding/removing agents/pipelines as toolkits
- changing selected agent/pipeline versions, rechecking icons for different versions
- saving and creating new agent versions, with different tools
- removing agent/pipeles as toolkits from custom versions rather than "latest"
- checking icons for agents/pipelines for different versions, on Run and Configuration tabs

No Issues.

@HawkQing1 No issue on Run tab as well.
