### ISSUE TITLE
[BUG] Toolkit name displays inconsistently during deletion when containing special characters

### ISSUE THREAD

**Issue by marara-h** [ProjectAlita/projectalita.github.io#1832]
**Steps to reproduce:**  
1. Create a toolkit with a name containing special characters (e.g., as2++"").  
2. Navigate to the table view and delete the toolkit.  
3. Observe the name displayed during the deletion confirmation.  
4. Open the same toolkit and delete it from the opened view.  
5. Observe the name displayed during the deletion confirmation.  

**Actual results:**  
- When deleting the toolkit from the table view, the name is displayed with special characters (e.g., as2++"").  
- When deleting the toolkit from the opened view, the name is displayed without special characters (e.g., as2).  

<img width="907" height="249" alt="Image" src="https://github.com/user-attachments/assets/1f4254bb-47fc-4c1f-a2ee-c853e87c8adc" />

<img width="951" height="319" alt="Image" src="https://github.com/user-attachments/assets/9ad7cab1-71c8-464b-96e4-c1377b07d47e" />
 

**Expected results:**  
- The toolkit name should be displayed consistently during deletion, regardless of whether it is deleted from the table view or the opened view.  

**Other info:**  
- The issue is specific to toolkit names containing special characters.  
- The toolkit is deleting in both cases on entering suggested name
- Some toolkits (e.g. Artifact doesn't take special characters as title, it is saved only as bucket name).

**Comment by HawkQing1** [comment]
@marara-h it should be fixed on dev, please verify it.

**Comment by marara-h** [comment]
@HawkQing1 
can still reproduce 

<img width="768" height="358" alt="Image" src="https://github.com/user-attachments/assets/d967495f-43be-4997-a9a4-32dd3e5eee71" />

**Comment by HawkQing1** [comment]
@marara-h it should be fixed on dev, please verify it.

**Comment by marara-h** [comment]
@HawkQing1 Verified on Dev env
