### ISSUE TITLE
[Enhancement Request] User must not be allowed to start a conversation while having broken agent/pipeline added as a participant

### ISSUE THREAD

**Issue by epamLDadayan** [ProjectAlita/projectalita.github.io#2079]
User must not be allowed to start a conversation while having broken agent/pipeline added 

Currently:

User can add as participants, broken agents and pipelines. They will be added as a participants, notifying users that they are broken (there are Misconfiguration errors). Such agents and pipelines can't be selected and used in the conversation itsef.
But if you have them in participants list your conversation will fail with error regardless you are using them or not as they are considered part of conversation.
This causes misuderstanding for users.

Suggestion: 
In case if user has added such broken agents or pipelines into the list of participants, make the conversation's Input field and Send icon "disabled" show a tooltip that "The conversation contains misconfigured agents/pipelines, fix or remove them before starting/continuing the conversation".

@plageat , @MikalaiB, @MykytaMorachovEpam , @HawkQing1 looking forward to your suggestions and how it can be implemented in a best way

**Comment by plageat** [comment]
Fixed in https://github.com/ProjectAlita/chat/commit/e1bab3ac2d229318463b19fdf7d05c1dbf210d01

Deployed to dev env, @epamLDadayan please check

**Comment by epamLDadayan** [comment]
@plageat Still not working, checked on DEV env

 
<img width="1863" height="843" alt="Image" src="https://github.com/user-attachments/assets/132f9951-50b1-4cde-b7c7-1d0701bb4780" />

**Comment by plageat** [comment]
Additionally fixed in https://github.com/ProjectAlita/chat/commit/f4e055473a4ccdfa993ccfc0b8f5eca5941d7c53

@epamLDadayan , please check on dev env

**Comment by epamLDadayan** [comment]
Verified on DEV

**Comment by epamLDadayan** [comment]
Verified on Stage env:
https://stage.elitea.ai/alita_ui/chat/53?name=Smoke+testing+conversation+for+stage
