### ISSUE TITLE
[BUG] Toolkit icons and tool names display incorrectly in Chat conversations during generation

### ISSUE THREAD

**Issue by epamLDadayan** [ProjectAlita/projectalita.github.io#2789]
**Title:** Toolkit icons and tool names display incorrectly in Chat conversations during generation

**Description:**  
When running tool calls in Chat → Conversations, toolkits display with incorrect or missing icons, and the used tool names appear only as tooltips instead of being shown as visible labels next to the toolkit. When the same agent runs in the Agents view, toolkits and tool names display correctly.

**Steps to Reproduce:**
1. Open Chat → Conversations.
2. Start a conversation with an agent that has toolkits attached.
3. Send a message that triggers a tool call.
4. Observe the toolkit icon and tool name display during/after generation.
5. Compare with the same agent running from Agents → Configuration view.

**Actual Result (in Chat → Conversations):**  
- Toolkit icons are incorrect or generic (e.g., wrench icon instead of the proper toolkit icon).
- Tool names (e.g., "stepback_summary_index") appear only as tooltips on hover.
- Tool names are not visibly displayed next to the toolkit icon.

**Expected Result:**  
Toolkits in Chat → Conversations should display the same way as in Agents:
- Show the correct toolkit icon (not a generic icon).
- Display the tool name as a visible label next to the toolkit icon (e.g., "aipdf" → "stepback_summary_index").
- Tool names should not require hovering to see; they should be immediately visible.

**Notes:**  
- The Agents view displays this correctly (first screenshot shows proper icon and visible tool name).
- Only Chat → Conversations has this display issue.

<img width="3708" height="1436" alt="Image" src="https://github.com/user-attachments/assets/21b9c353-e4d4-45e7-872f-44fee9625afd" />

<img width="2374" height="1452" alt="Image" src="https://github.com/user-attachments/assets/ec33ddba-9890-4c35-a9c8-9c06d9f49b61" />

**Comment by HawkQing1** [comment]
@epamLDadayan it should be fixed on dev, please verify it.

**Comment by epamLDadayan** [comment]
@HawkQing1 It works in general but for some toolkits still not working:

Figma
Memory
Zephyr
PowerPoint

CC: @MikalaiB

**Comment by HawkQing1** [comment]
@epamLDadayan the missed icons are added on dev, please verify it.
