### ISSUE TITLE
[BUG] Browser Toolkit: Unable to Select Any Tools Other Than Google Without Providing API Key

### ISSUE THREAD

**Issue by epamLDadayan** [ProjectAlita/projectalita.github.io#489]
**Description:**
When adding the Browser Toolkit to an agent, it is not possible to select any tools other than Google without providing an API Key and CSE ID. These fields are mandatory regardless of the selected tools, preventing the toolkit from being saved and added.

**Steps to Reproduce:**
1. Create an agent.
2. Add the Browser Toolkit.
3. Select any tool except Google.
4. Save and add the toolkit.

**Actual Result:**
The toolkit is not saved because the API Key field is mandatory, even though tools other than Google are selected.

**Expected Result:**
The toolkit should be saved and added, with the API Key and CSE ID fields being mandatory only if the Google tool is selected.

**Notes:**
- The current behavior forces users to provide API Key and CSE ID even when they are not using the Google tool, which is unnecessary and restrictive.

![Image](https://github.com/user-attachments/assets/6b56e45b-203f-403c-92e5-258909e41d74)

**Comment by HawkQing1** [comment]
@epamLDadayan This issue has been fixed by Artem @Aspect13. Please verify it on main. Thanks!

**Comment by epamLDadayan** [comment]
@Aspect13 this is not fixed. Checked on Main env, created a new agent from scratch and added a Browser toolkit. Getting the same notification. See screenshot:

![image](https://github.com/user-attachments/assets/bac14f67-0e3c-40af-ad2e-11d8bbfa612b)

**Comment by HawkQing1** [comment]
@epamLDadayan, I've fix it. Please verify it on main. Thanks!

**Comment by epamLDadayan** [comment]
Fixed, tested on Main env, can be included in the release.
