### ISSUE TITLE
[BUG] FE Issue when exporting prompt from different project

### ISSUE THREAD

**Issue by SamvelSimonyan** [ProjectAlita/projectalita.github.io#753]
**Steps to reproduce:**
Add a prompt from one project to a private collection

![Image](https://github.com/user-attachments/assets/ea29fc65-8db4-454c-9db0-f929f5d62e5c)

Go to private collections 
Export the item

**Actual results:**
FE error accrues 
https://github.com/user-attachments/assets/7d4f371b-2dbf-4c3e-ae99-24ca3cd0a30a

**Expected results:**
No errors occur

**Comment by SamvelSimonyan** [comment]
Created by  https://github.com/ProjectAlita/elitea_support/issues/124

**Comment by plageat** [comment]
Correct steps to reproduce:

1. Create prompt in public project
2. Publish prompt from public project to public project
3. Add published public prompt to private collection
4. Export the prompt

FE use correctly GET prompt details request for such prompt in public project, but same time sends private project_id instead of public_project_id in export GET API

**Comment by plageat** [comment]
BE related: prevent http 500 errors and return error reason
https://github.com/ProjectAlita/prompt_lib/commit/b08520820d3146954d0a840d63074b04c6880f9f

**Comment by HawkQing1** [comment]
@SamvelSimonyan, the FE crashing issue caused by failure of exporting has been fixed on main, the left issue is BE issue.

**Comment by plageat** [comment]
There is nothing to do with BE
Checked on main.
Not fixed on FE, still sends private project_id in the case, example:

`https://eye.projectalita.ai/main/api/v1/prompt_lib/export_import/prompt_lib/59/161?as_file=1`

@HawkQing1, please re-check

**Comment by HawkQing1** [comment]
@plageat I just fixed the crashing issue, currently the page should not crash even if the exporting api returns error. About the issue you pointed out, I will look into it.

**Comment by HawkQing1** [comment]
@SamvelSimonyan it's been fixed on main. Please verify it.
